### ISSUE TITLE
Laravel 5 support?

### ISSUE THREAD

**Issue by MartijnThomas** [prologuephp/alerts#11]
Can we expect Laravel 5 support in the near future? I'm currently using one of the forks, but I'm wondering I you are planning to make the package L5 ready :)

**Comment by driesvints** [comment]
Yes, absolutely! Just trying to find time for it. I'm moving to a new home this weekend so I probably won't have much time. I hope to do it by the end of next week.

**Comment by MartijnThomas** [comment]
Awsome! Good luck moving to your new place, there is no hurry, just informing :)

**Comment by MartijnThomas** [comment]
@driesvints First of all, setteled in your new home?

I'm sorry to bother you once again with this issue, but do you have an idea when you might be able to provide L5 support?

**Comment by michael-hopkins** [comment]
@MartijnThomas it looks like this fork has made the l5 changes. I can't say for certain though, just an assumption based on commit messages https://github.com/evanbarter/Alerts

**Comment by MartijnThomas** [comment]
@michael-hopkins Yeah I know, I've (for the time being) been using @evanbarter's fork aswell, but I prefer to use the 'official' version ;)

**Comment by driesvints** [comment]
I have a couple of hours now. I'll try to update it in a bit. Will let you know.

**Comment by driesvints** [comment]
@MartijnThomas @michael-hopkins I've released v0.4.0-beta.2 with L5 support for you guys to try out. Can you guys help test it out? https://github.com/prologuephp/alerts/releases/tag/0.4.0-beta.2

**Comment by driesvints** [comment]
Pushed 0.4.0-beta.3 with a fix.

**Comment by MartijnThomas** [comment]
Thanks!! I'll dive into it later today!

**Comment by MartijnThomas** [comment]
@driesvints Didn't get around to it yesterday, but looked at it today, It seems to be working fine.

**Comment by driesvints** [comment]
@MartijnThomas ok, I'll tag stable release later today then.

**Comment by MartijnThomas** [comment]
@driesvints one thing though, I think Laravel 5 does not support cascading configuration files in nested folders (has something todo with config cache I believe). Currently the config file is publisched to a package dir. But I'm not entierly sure

**Comment by meetraz** [comment]
Any way you could add middleware to share alerts with all views?  Similar to L5's Illuminate\View\Middleware\ShareErrorsFromSession

**Comment by driesvints** [comment]
@MartijnThomas have you had time to test this? Because I'm gonna close this if this isn't a real issue. I don't have time atm to test this myself.

**Comment by driesvints** [comment]
@meetraz I don't have time atm to do that myself. You can always send in a pull request if you like. Also: if you want this to get tracked, create a separate feature request issue.
