### ISSUE TITLE
Can't update Laravel 4.2 app with composer

### ISSUE THREAD

**Issue by DA40** [prologuephp/alerts#12]
In the require block of my composer.json file for a Laravel 4.2 app, I had "prologue/alerts": "dev-master", so it served me right when you released the version for Laravel 5 and composer update failed.  However, after changing that to "prologue/alerts": "0.3.*", I get the following error:

[Composer\Downloader\TransportException]
The "https://api.github.com/repos/driesvints/Alerts/zipball/3a0c4d2c2a8981f9c623065e73813f0e648b5c74" file could not be downloaded (HTTP/1.1 404 Not Found)

I intend to update my application to Laravel 5.x, but in the meantime, how do I get a compatible version of Alerts?

Thanks,
Keith

**Comment by driesvints** [comment]
That's odd. The release is still available both on Github and Packagist. Seems like composer has a problem with downloading the tarball from Github.

Can you try again with the `--prefer-source` flag?

**Comment by DA40** [comment]
Thanks for your response.

 

I just ran the update again, leaving composer.json as:

 

        "require": {

                "laravel/framework": "4.2.*",

                "prologue/alerts": "0.3.*"

        },

 

The output this time was:

 

Loading composer repositories with package information

Updating dependencies (including require-dev)

  - Installing prologue/alerts (v0.3.0)

    Downloading: connection...

    Failed to download prologue/alerts from dist: The "https://api.github.com/repos/driesvints/Alerts/zipball/3a0c4d2c2a8981f9c623065e73813f0e648b5c74" file could not be downloaded (HTTP/1.1 404 Not Found)

    Now trying to download from source

  - Installing prologue/alerts (v0.3.0)

    Cloning 3a0c4d2c2a8981f9c623065e73813f0e648b5c74

 

So, I’m getting the version I need from source rather than a zipball.  This is a bit scrappy, but gets me going again.

 

Regards,

Keith

**Comment by driesvints** [comment]
Yep, just seems like there's an authentication error with Github. I suggest you pick this up with the composer team because I doubt that it has anything to do with this package specifically.
