### ISSUE TITLE
Clearing all flash messages?

### ISSUE THREAD

**Issue by baj84** [prologuephp/alerts#15]
Is there a way to clear all current flash messages in the bag?

Cheers

**Comment by MickaelTH** [comment]
Looking for the same. As Alert is a MessageBag there is no method to flush:

https://laravel.com/api/5.1/Illuminate/Support/MessageBag.html

Maybe Am I missing something here, but I don't think it's possible. Alert::add yes, but Alert::flush nope :)

**Comment by lloy0076** [comment]
You'd need to do something like:

```
$serviceProvider = resolve('\\Prologue\\Alerts\\MessageBag');
$config               = $serviceProvider->getConfig();
$key                   = $config['alert_messages'];

request()->session()->forget($key);
```

There **are** faster ways to do that (e.g. you could just reach into `config(alerts.alert_messages)` without resolving the alerts service provider.

**Comment by MickaelTH** [comment]
Hi @lloy0076 Thank you for your help. I've tried but no success:

![2017-10-09 002182](https://user-images.githubusercontent.com/26375917/31345155-10fcd2d6-ad3f-11e7-83ca-0d1f2302a765.png)

I also tried:

`request()->session()->forget(config('prologue.alerts.session_key'));`

But nothing happen the default alert is still triggered when creating new item. If only a custom message could be sent to the CrudController at storeCrud() or if we could temporary override the backpack::crud.insert_success string...

![2017-10-09 002181](https://user-images.githubusercontent.com/26375917/31345074-d1ea3f16-ad3e-11e7-8093-9607e37a4d31.png)

For info, I have of course tried those codes after the:

`$redirect_location = parent::storeCrud($request);`

**Comment by ccyeh0901** [comment]
Hello, in my case why \Alert::success(trans('backpack::crud.insert_success'))->flash(); not showing any message box after redirecting to some url , but it does show message when return to some view, please help, thanks a lot~

**Comment by MickaelTH** [comment]
@ccyeh0901 I don't think this is the same issue - you may need to open another ticket. Meanwhile, have you locked at this: https://laravel.com/docs/5.5/responses#redirecting-with-flashed-session-data

**Comment by Gummibeer** [comment]
Sorry if I commited two PRs. My GitHub shows no one. :/ So I Hope that it will come back.

**Comment by tabacitu** [comment]
Thanks for the PR @Gummibeer ! Merging now!
