### ISSUE TITLE
No Autoload Functionality for L5.5

### ISSUE THREAD

**Issue by lloy0076** [prologuephp/alerts#18]
This needs something similar to:

```
    "extra": {
        "laravel": {
            "providers": [
                "Backpack\\Base\\BaseServiceProvider"
            ]
        }
}
```

There's probably also an alias needed too.

**Comment by tabacitu** [comment]
Fixed! Thank you @lloy0076 !

**Comment by tabacitu** [comment]
Wish we had more repositories like this one :-))

![screen shot 2018-02-12 at 13 23 55](https://user-images.githubusercontent.com/1032474/36094725-09cef360-0ff8-11e8-96f4-b9f1e09b2746.png)
