### ISSUE TITLE
Alerts::hasAny()

### ISSUE THREAD

**Issue by AbbyJanke** [prologuephp/alerts#29]
Would be nice to be able to see if there are currently any alerts set. Useful for only including certain JS/CSS when there are alerts.

**Comment by tabacitu** [comment]
I agree, it would be nice! Shouldn't be too difficult to achieve. Not sure on the naming though. Possible options:
- ```Alert::count()```
- ```Alert::has()```
- ```Alert::hasAny()```

I guess the broadest would be ```Alert::count()```, and it has the benefit of being able to use it to know how many alerts there are... Not 100% about this though. 

Until then @AbbyJanke  I think you can use ```count(\Alert::getMessages())```

**Comment by AbbyJanke** [comment]
I'm thinking `Alert::has()` is the better option looking through it.

So Laravel has '[Arr::hasAny()](https://laravel.com/docs/7.x/helpers#method-array-hasany)' to see if an array has a key based on a dot notation.

The Validation package uses `$errors->has('fieldName')` to determine if an error exists.

Therefore just `has()` feels more consistent. Also would be nice to be able to pass an optional parameter of a 'level name' to count only those specifically.

**Comment by AbbyJanke** [comment]
Created PR with further details. Closing this one.
