### ISSUE TITLE
Is there a way to inject a session?

### ISSUE THREAD

**Issue by joelmellon** [prologuephp/alerts#34]
I'm trying to `Alert::add()` messages from a Laravel Job (ShouldQueue) which is run asynchronously. I've tried instantiating my own AlertsMessageBag and injecting a user session (passed into my Job from a controller) but it appears that the underlying Illuminate\Support\MessageBag doesn't save anything to the session. So where are alerts saved?

Can I add alerts to the user's original browser session from outside the session context so that on next page load they'll see the status of the completed job (using `Alerts::all()`)?

**Comment by joelmellon** [comment]
This is what I've tried. Where `$userSession` was `$request->session()` that I passed into the Job from my controller. I can confirm that inside my Job's handle() method `$userSession` is indeed the original session (same id when dumped controller).

My alert is written into the passed in session but not `Alert::all()` either from the Job or on next page load.

Here's within the Job's handle() method:
```
(new AlertsMessageBag($userSession, Alert::getConfig()))->add('info', 'test')->flash();
dd($this->alertsMessageBag->getSession()->get('alert_messages')); // ['info' => [0 => 'test']]
dd(Alert::all()); // []
```

**Comment by sergiz** [comment]
You are trying to achieve something that is not really viable.

For your use case I suggest you to look into database notifcations:
https://laravel.com/docs/8.x/notifications#database-notifications

**Comment by pxpm** [comment]
Indeed @sergiz , and thanks for helping @joelmellon here. 

Session is unviable for what you want to achieve. Database notifications is one way to go here, and pretty much solve the issue you are facing. 

When you get those database notifications you build the `Alert` and show to the user. Not in the job. 

Best,
Pedro
