### ISSUE TITLE
Requiring type of Illuminate\Config\Repository

### ISSUE THREAD

**Issue by mah484** [prologuephp/alerts#42]
I am trying to use a package that also uses Prologue.  In my project, I have included another third party package, [Laravel Persistent Configuration Repository](https://github.com/illuminatech/config).

When using these together, I get an error that Prologue requires a type of `Illuminate\Config\Repository` and instead a type of `Illuminatech\Config\PersistentRepository` is being sent.  I have not gone deep enough into both Prologue and this package to see at what point the latter is being used instead of the former.  I can put together something to reproduce this issue, but it will be quite large and take significant time.

Before I do this, I just wanted to inquire about something and whether it is an _issue_ at all or a feature request.  The [repository being sent](https://github.com/illuminatech/config/blob/master/src/PersistentRepository.php) implements the `RepositoryContract`.  Therefore, should passing this not be supported for use in Prologue, or any other package that may implement this contract?  I hope my understanding is correct here, but it definitely seems like this would allow Prologue to [work better](https://laravel.com/docs/9.x/contracts#when-to-use-contracts) with other packages.

If it is useful, the full error message from my environment is:

`Prologue\Alerts\AlertsMessageBag::__construct(): Argument #2 ($config) must be of type Illuminate\Config\Repository, Illuminatech\Config\PersistentRepository given, called in /vagrant/src/laravel-8/vendor/prologue/alerts/src/AlertsServiceProvider.php on line 28`

**Comment by tabacitu** [comment]
Sorry to reply so late. It sounds feasible, yes. If you can save the time to create a PR so it works better with other packages, happy to take a look, review, polish and merge.

Thanks!
